<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>name</key>
	<string>J80 ASM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(a|b|c|d|e|f|x|y|ba|cd|ef|xy|ix|iy|sp|fp)\b</string>
			<key>name</key>
			<string>storage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\.ascii|.asciiz|length|\.entry|\.stackbase|\.bytes|\.words)(?-i)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]|,|\(|\)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(ld|st|mov|nop|store|load|cmp|add|adc|sub|sbc|and|xor|or|not|lf|sf|sext|push|pop|lsh|rsh)\b</string>
			<key>name</key>
			<string>support.function.j80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)((jmp|call|ret)(|c|nc|z|nz|v|nv|n|nn))\b</string>
			<key>name</key>
			<string>support.function.j80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\s+)(\#)?-?(((0x|&amp;)[0-9a-fA-F])|[0-9a-fA-F]+h)+\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\s+)\#-?[0-9a-zA-Z_]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\s+)0b?[01]+\b</string>
			<key>name</key>
			<string>constant.numeric.literal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\s+)[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.'</string>
			<key>name</key>
			<string>string.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+\".+\"</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^.+)(\:)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z0-9_]+</string>
			<key>name</key>
			<string>variable</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.j80</string>
	<key>uuid</key>
	<string>91164AFE-632B-4AC5-A8C0-66E5FC958CB2</string>
</dict>
</plist>
